[package]
name = "day8"
version = "0.1.0"
authors = ["Daniel Soto <danielsoto.3004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
lazy_static = "*"
